# Server settings
server:
  port: 9002

# Spring
spring:
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true

# Lucene
lucene:
  dataFile: /home/shengsheng/Workspaces/IR/resources/Posts.xml
  indexPath: /home/shengsheng/Workspaces/IR/projects/app-answering-user-ranking/index
  rankingFile: /home/shengsheng/Workspaces/IR/projects/app-answering-user-ranking/index/ranking.data
  willIndex: false
  maxUserCount: 20000
