# Server
server:
  port: 9001

# Spring
spring:
  http:
    encoding.charset: UTF-8
    encoding.enable: true
    encoding.force: true

# Lucene
lucene:
  dataFile: /home/shengsheng/Workspaces/IR/resources/Posts.xml
  indexPath: /home/shengsheng/Workspaces/IR/projects/app-language-trend/index
  willIndex: false
  rankLanguages: java, c, c++, c#, python, php, javascript, swift, objective-c, ruby, perl, go
  startYear: 2008
  endYear: 2016
  trendFile: /home/shengsheng/Workspaces/IR/projects/app-language-trend/index/trend.data
