var d = {base : ""};
document.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"jqplot/jquery.jqplot.min.js\"><\/script>");  
document.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"jqplot/examples/syntaxhighlighter/scripts/shCore.min.js\"><\/script>"); 
document.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"jqplot/examples/syntaxhighlighter/scripts/shBrushJScript.min.js\"><\/script>"); 
document.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"jqplot/examples/syntaxhighlighter/scripts/shBrushXml.min.js\"><\/script>"); 
document.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"jqplot/plugins/jqplot.logAxisRenderer.min.js\"><\/script>"); 
document.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"jqplot/plugins/jqplot.canvasTextRenderer.min.js\"><\/script>"); 
document.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"jqplot/plugins/jqplot.canvasAxisLabelRenderer.min.js\"><\/script>"); 
document.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"jqplot/plugins/jqplot.canvasAxisTickRenderer.min.js\"><\/script>"); 
document.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"jqplot/plugins/jqplot.dateAxisRenderer.min.js\"><\/script>"); 
document.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"jqplot/plugins/jqplot.categoryAxisRenderer.min.js\"><\/script>");  
document.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"jqplot/plugins/jqplot.barRenderer.min.js\"><\/script>");  
document.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"jqplot/plugins/jqplot.pointLabels.min.js\"><\/script>");  
document.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"jqplot/plugins/jqplot.dateAxisRenderer.min.js\"><\/script>");  
document.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"jqplot/plugins/jqplot.dateAxisRenderer.min.js\"><\/script>");  
document.write("<link class=\"include\" rel=\"stylesheet\" type=\"text/css\" href=\"jqplot/jquery.jqplot.min.css\" />");
document.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"jqplot/examples/syntaxhighlighter/styles/shCoreDefault.min.css\" />");
document.write("<link type=\"text/css\" rel=\"stylesheet\" href=\"jqplot/examples/syntaxhighlighter/styles/shThemejqPlot.min.css\" />"); 
document.write("<script language=\"JavaScript\" type=\"text/javascript\" src=\"m_jqplot.js\"><\/script>"); 
